---
title: "Philippe Heymans Smith"
date: "`r Sys.Date()`"
author: 'Data Scientist'
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

#### Heredia, Costa Rica ⬝ (+506) 8447-8088 ⬝ pheymanss@gmail.com ⬝ https://github.com/pheymanss/

Equipped with pure mathematics-level of rigour, I found a deep passion for statistics and recognized machine learning models as the pinnacle of where that knowledge could take us. Experienced in supervised and unsupervised big data classification and regression problems, I strive to leverage my theoretical and programming skills to improve people's lives.

## Education

Data ScienceTech Institute, (2020 - Ongoing).  
Applied MSc in Data Science & Artificial Intelligence.

Universidad de Costa Rica, School of Mathematics (2013 - 2018).  
Bachelor of Science, Actuarial Science.

## Technical Skills

```{r fig.width=6, fig.height=6, fig.align='center'}
technical_skills <- c(
  'Deep understanding of sophisticated machine learning modelling techniques such as:
                  - Tree models (tree bosting, Random Forests, XGBoost)
                  - gradient boosted machines
                  - DBSCAN
                  - gaussian mixture clustering
                  - neural networks
                  - model ensambling
                  - encoding',
  'Advanced knowledge in R development (outstanding proficiency with data.table and purrr)',
  'R package development with impeccable documentation',
  'Advanced knowledge in data visualization (and high proficiency with ggplot)',
  'Proven experience in big (200MM+) data analysis',
  'Solid SQL knowledge',
  'Solid knowledge of general design principles',
  'Solid understanding of distributed file systems',
  'Solid Shiny app development skills',
  'Basic knowledge of Python')
```

## Profesional Experience

**Mastercard SJO Center of Excellence**  
Associate Consultant, Advanced Analytics.  
San José, Costa Rica. July 2019 -- Present

*	Development and delivery of advanced analytics products for several financial institutions across the continent, leveraging the hundreds of GB of transactional data the company holds. Deliveries ranged from customer behavioural segmentations, post hoc campaign performance diagnostics, product migration models, authorizations and fraud diagnostics, data quality assessments, among many other minor efforts. 
* All project deliveries included throughout technical and methodological presentations to both internal and external project stakeholders, from mostly non-technical backgrounds.
*	Development of two proprietary, in-house, multi-purpose R packages including over 84 fully generalized functions ready to work on any given dataset, aiming to leverage advanced R programming knowledge and make it immediately accessible to less technically-proficient team members.
* Designed and imparted R trainings for non-specialist teams from the same vertical in Brazil, México, Colombia, Uruguay, Argentina and Costa Rica, along monthly trainings imparted to my own specialist team.

**Quanto Soluciones Analíticas y Cuantitativas S.A.**  
Financial Analyst, Mathematical Modeling Department  
San José, Costa Rica. April 2018 – July 2019

* Rewrote the R calibration algorithm for Liquidity Risk indicators' sensibility against national and international macroeconomic indexes.
* Spearheaded the installation of 10 additional features of a proprietary Liquidity Risk analysis tool for the second largest bank in Costa Rica. 
*	Provided both technical and methodological support for several financial institutions in the use for the company’s various risk analysis tools.
*	Maintained an amicable relationship with high profile personnel from our clients as the face of the company.

## Academic Experience

**Generalized Sentiment Scoring of Short Informal Text in Spanish**  
Natural Language Processing  
Developed in R, Aug 2016 - Jul 2017

- Fitting text sentiment scoring into a rigorous mathematical framework, we constructed a signed measure function and created a language-agnostic and category-agnostic text classification tool. 

**Flower Market Analysis Through Google Web Searches**  
Time Series Analysis  
Developed in R, Nov 2017 - Dec 2017

- Using basic time series analysis frameworks like ARIMA(p,q) models, we characterized the fluctuations and expected growth rate of the flower market based on time series analysis using web searches of the word “flower.”

**Betting Strategy Evaluation of Online MLB Matches**  
Backtesting  
Developed in VBA, Jun 2016 - Jul 2016

- We simulated the performance of several betting strategies for an individual with no prior sports knowledge, based solely on information that can be subtracted from online betting websites. We developed and tested a modified Martingale strategy which provided a high chance of profit in any subset of the time interval studied. 

## Experience - Other

**TECHO-COSTA RICA**  
San José, Costa Rica  
April 2011 – March 2015

-	As the Corporate Volunteering Division Coordinator, I restructured the NGO’s approach to corporate volunteering projects, corporate trainings, project executions, and post-project evaluation.
-	As a member of the Logistics team, I collaborated in the coordination of 34 medium scale (50-200 people) projects, including emergency housing infrastructure and country-wide fundraising campaigns.
-	As coordinator of Staff Management, I led the refinement of the inner processes behind personnel recruiting and requirement standardization for all positions on our short-term projects.
