---
title: "Philippe Heymans Smith"
date: "`r Sys.Date()`"
author: 'Científico de Datos'
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

#### Heredia, Costa Rica ⬝ (+506) 8447-8088 ⬝ pheymanss@gmail.com ⬝ https://github.com/pheymanss/

Equipado con un rigor similar a un matemático puro, desarrollé una profunda pasión por la estadística, y reconocí los modelos de machine learning como el pináculo de adonde este conocimiento puede llevarnos. Experimentado en problemas de regresión y clasificación tanto supervisados como no supervisados, apunto a apalancar mis habilidades teóricas y de programación para mejorar las vidas de las personas.

## Educación

Data ScienceTech Institute, (2020 - Presente).    
Maestría Aplicada, Ciencia de Datos e Inteligencia Artificial

Universidad de Costa Rica, Escuela de Matemática (2013 - 2018).  
Bachillerato, Ciencias Actuariales

## Habilidades técnicas

```{r fig.width=6, fig.height=6, fig.align='center'}
habilidades_tecnicas <- c(
  'Dominio avanzado de desarrollo en R (con excepcional dominio de data.table y purrr)',
  'Desarrollo de paquetes de R con documentación impecable',
  'Conocimiento avanzado en visalización de datos (con gran dominio de ggplot)',
  'Sólidas habilidades en desarrollo de aplicaciones Shiny',
  'Conocimiento sólido en principios de diseño',
  'Conocimiento sólido en Excel y VBA',
  'Conocimiento básico en SQL',
  'Conocimiento básico de Python')
```

## Experiencia Profesional

**Mastercard SJO Center of Excellence**  
Associate Consultant, Advanced Analytics.  
San José, Costa Rica. July 2019 -- Present

* Desarrollo y entrega de sofisticados productos de análisis de datos para gran variedad de entidades financieras de todo el continente, apoyados en los cientos de GB de data transaccional que sostiene la compañía. Las entregas abarcan segmentaciones comportamentales de clientes, análisis post hoc de desempeño de campañas, modelos de migración de productos, diagnósticos de autorizaciones y fraudes, asesoramientos de calidad de data, entre otros esfuerzos menores.
* Todos los proyectos contemplan detalladas presentaciones técnicas y metodológicas, tanto para stakeholders internos como externos, de perfiles mayoritariamente no técnicos.
* Desarrollo de dos paquetes de R propietarios multi-propósito para uso interno. Una colección de más de 60 funciones generalizadas para uso sobre cualquier set de datos, con el fin de apalancar mi avanzado conocimiento en R y hacerlo inmediatamente accesible a miembros menos técnicamente versados del equipo.
* Diseño de capacitaciones en R impartidas a equipos no especialistas en Brasil, México, Colombia, Uruguay, Argentina y Costa Rica, adicional a capacitaciones mensuales para mi propio equipo de especialistas.

**Quanto Soluciones Analíticas y Cuantitativas S.A.**  
Analista Financiero, Departamento de Modelos Matemáticos  
San José, Costa Rica. April 2018 – July 2019

* Reescritura en R del algoritmo de calibración de sensibilidad de indicadores de liquidez frente a indicadores macroeconómicos nacionales e internacionales.
*	Ejecución de la instalación de 10 nuevas funcionalidades de una herramienta propietaria de análisis de riesgo de liquidez para el segundo banco más grande de Costa Rica. 
* Apoyo técnico y metodológico en el uso de varias herramientas de análisis para varias instituciones financieras


## Experiencia Académica

**Clasificación de sentimientos en textos cortos e informales en español**
 
Procesamiento de Lenguaje Natural  
Desarrollado en R, Ago 2016 - Jul 2017

- Enmarcando el clásico problema de clasificación de sentimientos en una rigurosa construcción matemática de una medida signada, creamos una herramienta de clasificación de texto para cualquier idioma arbitrario, y sobre cualquier dicotomía de sentimientos.

**Análisis del mercado de flores a través de tendencias de búsquedas en Google**  
Análisis de series de tiempo  
Desarrollado en R, Nov 2017 - Dic 2017

- Utilizando modelos básicos de análisis de series de tiempo como lo son los modelos ARIMA(p,q), caracterizamos las fluctuaciones y crecimiento esperado del mercado de flores basándonos en la serie de tiempo de búsquedas de la palabra 'flower'.


**Estrategias de apuestas en línea sobre partidos de la MLB**  
Backtesting  
Desarrollado en VBA, Jun 2016 - Jul 2016


- Simulamos el desempeño de distintas estrategias de apuestas que podría jugar un individuo sin conocimiento del deporte, basándose solamente en información extraída de páginas de apuestas en línea. Desarrollamos una estrategia de Martingala modificada con altas probabilidades de ganancias en cualquier subconjunto del periodo estudiado.

## Experiencia Extracurricular

**TECHO-COSTA RICA**  
San José, Costa Rica  
April 2011 – March 2015

- Como Coordinador de Voluntariado Corporativo, replanteé la forma en que la organización se aproximaba a proyectos de voluntariado corporativo, incluyendo las capacitaciones, ejecución de los proyectos y evaluación posterior.
- Como miembro del equipo de Logística, colaboré en la coordinación de 34 projectos de gran escala, incluyendo la construcción de soluciones transitorias de vivienda y colectas nacionales.
- Como coordinador de gestión de staff, dirigí el refinamiento de los procesos internos de reclutamiento y estandarización de requerimientos para todas las posiciones de los proyectos de corto plazo.
